### ISSUE TITLE
Writing to seaweed volume eat out my root partition space 

### ISSUE THREAD

**Issue by liyimeng** [chrislusf/weed-fs#2281]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/chrislusf/seaweedfs/discussions

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**

I follow the seaweed operator and csi driver page to to run a simple test with fio in /data which is a seaweed volume created from seaweed csi driver. After a while, my root partition is full and k8s node frozen.  I have no clue how to reclaim the space.  Have to format the entire disk to get back the space. 

I delete the sample pod, nothing help either. 

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".

```
master0 [~]$ kubectl -n seaweed get pod -o wide 
NAME                READY   STATUS    RESTARTS   AGE   IP           NODE      NOMINATED NODE   READINESS GATES
seaweed1-filer-0    1/1     Running   0          81m   10.42.2.34   master0   <none>           <none>
seaweed1-filer-1    1/1     Running   0          81m   10.42.1.16   master1   <none>           <none>
seaweed1-master-0   1/1     Running   0          82m   10.42.2.33   master0   <none>           <none>
seaweed1-master-1   1/1     Running   0          82m   10.42.2.32   master0   <none>           <none>
seaweed1-master-2   1/1     Running   0          82m   10.42.1.15   master1   <none>           <none>
seaweed1-volume-0   1/1     Running   0          81m   10.42.2.36   master0   <none>           <none>

```

- OS version
 ubuntu 20.04 

- output of `weed version`

```
apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweed1
  namespace: seaweed 
spec:
  # Add fields here
  image: chrislusf/seaweedfs:2.59
  volumeServerDiskCount: 1
  hostSuffix: seaweed.abcdefg.com
  master:
    replicas: 3
    volumeSizeLimitMB: 1024
  volume:
    replicas: 1
    requests:
      storage: 4Gi
  filer:
    replicas: 2
    config: |
      [leveldb2]
      enabled = true
      dir = "/data/filerldb2"

```
- if using filer, show the content of `filer.toml`

**Expected behavior**

seaweed should write data into its volume, but not feed my root partition 

**Screenshots**

Before starting the test, I have about 14GB available disk at /, after test, I only have  2.2GB

And there is no way to reclaim it, it seem went into a black hole. 

```
/ # df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  15.7G     12.7G      2.2G  85% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     3.8G         0      3.8G   0% /sys/fs/cgroup
seaweed1-filer.seaweed.svc:8888:/buckets/pvc-0c57c8cf-8996-4f84-80b8-132d490d8cda
                          4.0G         0      4.0G   0% /data
/dev/vda1                15.7G     12.7G      2.2G  85% /etc/hosts
/dev/vda1                15.7G     12.7G      2.2G  85% /dev/termination-log
/dev/vda1                15.7G     12.7G      2.2G  85% /etc/hostname
/dev/vda1                15.7G     12.7G      2.2G  85% /etc/resolv.conf
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                     3.8G     12.0K      3.8G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                     3.8G         0      3.8G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                     3.8G         0      3.8G   0% /proc/scsi
tmpfs                     3.8G         0      3.8G   0% /sys/firmware

```

**Additional context**
