### ISSUE TITLE
seaweedfs externalDatabase "postgresql" connection error.

### ISSUE THREAD

**Issue by abdul90082** [chrislusf/weed-fs#5985]
` values.yml `
```
master:
  replicaCount: 1
  persistence:
    enabled: false
    
filer:
  enabled: true
  replicaCount: 1
  existingConfigmap: "my-seaweedfs-filer-config"
  
s3:
  enabled: true
  replicaCount: 1
  auth:
    enabled: true
    existingSecret: "my-secret-integrations"
mariadb:
  enabled: false

externalDatabase:
  enabled: true
  host: "seaweedfs-postgres-cluster.seaweedfs-databases.svc.cluster.local:5432/seaweedfs_postgres_cluster"
  user: "postgres"
  existingSecret: "postgres.seaweedfs-postgres-cluster.credentials.postgresql.acid.zalan.do"
  database: "seaweedfs_postgres_cluster"
  port: 5432
  
  ```
  ` my-seaweedfs-filer-config.yaml ` ConfigMap:
  ```
  resource "kubernetes_config_map" "my_seaweedfs_filer_config" {
 metadata {
   name      = "my-seaweedfs-filer-config"
   namespace = local.namespace
 }

 data = {
   "filer.toml" = <<-EOT
     [postgres2]
     enabled = true
     user = "postgres"
     sslmode = "disable"
     database =  "seaweedfs_postgres_cluster"
     address = "seaweedfs-postgres-cluster.seaweedfs-databases.svc.cluster.local"
     password = "some-pasword"
     port = 5432  
     # connection_limit = 10 
   EOT
 }
}
```
` postgres.${var.name}-postgres-cluster.credentials.postgresql.acid.zalan.do ` Secret:
```
resource "kubernetes_secret" "postgres_user_filer" {
  metadata {
    name      = "postgres.${var.name}-postgres-cluster.credentials.postgresql.acid.zalan.do"
    namespace = "seaweedfs"
    labels = {
      # application  = "spilo"
      # cluster-name = "${var.name}-postgres-cluster"
      # team         = var.name
    }
  }

  data = {
    mariadb-password = var.postgres_admin_password
  }
}
```

**What is the expected behavior?**
s3, filer pod should come up

**What do you see instead?**
Getting error in filer due to s3 is not coming up
Its trying to connect to localhost:
```
F0906 10:18:45.751041 configuration.go:25 failed to initialize store for postgres2: connect to connect_timeout=30 port=5432 sslmode=disable user=postgres password=ADAPTED dbname=seaweedfs_postgres_cluster search_path=public error:dial tcp 127.0.0.1:5432: connect: connection refused
```

**Additional information**
Let me know if there's anything you need me to do to reproduce it.

Thanks!
