### ISSUE TITLE
Reading s3 objects randomly gets 'write: broken pipe' 

### ISSUE THREAD

**Issue by amir-latifi** [chrislusf/weed-fs#6263]
Hi, 

I have seaweed cluster with this config:
weed version: 3.63
replication: 010
filerstore: scyllaDB
The requests are sent to filer (which its s3 is enabled) via Traefik (ingress controller)
The components are deployed on kubernetes cluster and filer's replica count is 2

After a burst copy of 1.6 TB of data using aws cli, when I try to read objects, some of them randomly get this error:

```
I1120 13:47:57.798120 s3api_object_handlers.go:461 passthrough response read 293732352 bytes: write tcp 10.0.46.84:8333->10.0.2.55:54438: write: broken pipe
```
It seems in this case the object is not downloaded completely and the download process has been 
But sometimes they are downloaded completely and correctly. It's good to note that the traefik always see 200 in status code. 

**I have checked the network status and it's fine.** 
For example, I have seen these errors for a single object in a row (Look at the dataLenght. They all have same value): 
![image](https://github.com/user-attachments/assets/ed986121-5192-419d-9dc1-bf4df3e5f82f)

**Also we have not have any disk failure or issue.** 

I have multiple questions:
1. What are the possible causes of this problem? 
2. Is it possible that the object be healthy on one of the replicas and unhealthy on the other? What will happen when we read the object? Which replica will serve the object? In this case how can I solve the problem? 
3. What will happen if one or multiple chunks of data is missed or corrupted? Does the filer or s3 return any error or they will send the incomplete response to receiver? 
4. Generally in which cases does the s3 or filer breake the pipe? 
5. Is there any self-healing mechanism in seaweedfs that after getting some errors, fixes the object? 

These are the important flags which I started the filer and s3 with:
```   
Filer:
    - name: ENCRYPTVOLUMEDATA
      value: "false"
    - name: WEED_FILER_OPTIONS_RECURSIVE_DELETE
      value: "false"
    - name: MAXMB
      value: "8"
    - name: S3
      value: "true"
    - name: DISK
      value: hdd
    - name: DEFAULTREPLICAPLACEMENT
      value: "010"
```

```
Volume Server:
    - name: MAX
      value: "0"
    - name: IDLETIMEOUT
      value: "600"
    - name: READBUFFERSIZEMB
      value: "8"
    - name: HASSLOWREAD
      value: "true"
    - name: RACK
      value: d4e2146a7ad3f48c750609a6fae28929
    - name: DISK
      value: hdd
```
